behaviors:
  DroneBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 0.0005
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 1024
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 0.0005
    init_path: null
    keep_checkpoints: 10
    max_steps: 500000
    checkpoint_interval: 50000
    time_horizon: 64
    summary_freq: 10000